# Simple Test Constraints for Basys3 (xc7a35tcpg236-1)
# Based on Basys3 Master XDC

# Clock - 100MHz
set_property LOC W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Reset - Using SW15 as active-low reset
set_property LOC R2 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

# Switches (SW0-SW14, SW15 used for reset)
set_property LOC V17 [get_ports {sw[0]}]
set_property LOC V16 [get_ports {sw[1]}]
set_property LOC W16 [get_ports {sw[2]}]
set_property LOC W17 [get_ports {sw[3]}]
set_property LOC W15 [get_ports {sw[4]}]
set_property LOC V15 [get_ports {sw[5]}]
set_property LOC W14 [get_ports {sw[6]}]
set_property LOC W13 [get_ports {sw[7]}]
set_property LOC V2 [get_ports {sw[8]}]
set_property LOC T3 [get_ports {sw[9]}]
set_property LOC T2 [get_ports {sw[10]}]
set_property LOC R3 [get_ports {sw[11]}]
set_property LOC W2 [get_ports {sw[12]}]
set_property LOC U1 [get_ports {sw[13]}]
set_property LOC T1 [get_ports {sw[14]}]
# SW15 (R2) is used for rst_n, so we only have 15 switches available
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
# sw[15] IOSTANDARD but no LOC - let it float or be optimized away
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

# Buttons (BTNC=btn[0], BTNR=btn[1], BTNL=btn[2], BTND=btn[3], BTNU=btn[4])
set_property LOC U18 [get_ports {btn[0]}]
set_property LOC T17 [get_ports {btn[1]}]
set_property LOC W19 [get_ports {btn[2]}]
set_property LOC U17 [get_ports {btn[3]}]
set_property LOC T18 [get_ports {btn[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[4]}]

# LEDs
set_property LOC U16 [get_ports {led[0]}]
set_property LOC E19 [get_ports {led[1]}]
set_property LOC U19 [get_ports {led[2]}]
set_property LOC V19 [get_ports {led[3]}]
set_property LOC W18 [get_ports {led[4]}]
set_property LOC U15 [get_ports {led[5]}]
set_property LOC U14 [get_ports {led[6]}]
set_property LOC V14 [get_ports {led[7]}]
set_property LOC V13 [get_ports {led[8]}]
set_property LOC V3 [get_ports {led[9]}]
set_property LOC W3 [get_ports {led[10]}]
set_property LOC U3 [get_ports {led[11]}]
set_property LOC P3 [get_ports {led[12]}]
set_property LOC N3 [get_ports {led[13]}]
set_property LOC P1 [get_ports {led[14]}]
set_property LOC L1 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

# 7-Segment Display
set_property LOC W7 [get_ports {seg[0]}]
set_property LOC W6 [get_ports {seg[1]}]
set_property LOC U8 [get_ports {seg[2]}]
set_property LOC V8 [get_ports {seg[3]}]
set_property LOC U5 [get_ports {seg[4]}]
set_property LOC V5 [get_ports {seg[5]}]
set_property LOC U7 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

# Decimal Point
set_property LOC V7 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]

# 7-Segment Anodes
set_property LOC U2 [get_ports {an[0]}]
set_property LOC U4 [get_ports {an[1]}]
set_property LOC V4 [get_ports {an[2]}]
set_property LOC W4 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

# UART (USB-RS232 Interface)
set_property LOC B18 [get_ports uart_tx]
set_property LOC A18 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]

# Configuration options
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
